package com.masai.uber.utlis

import android.graphics.Color

const val KEY_DRIVER_LOCATION_REFERENCE = "DriverLocation"

const val KEY_DRIVER_LOGGED_IN = "KEY_DRIVER_LOGGED_IN"
const val KEY_DRIVER_DISPLAY_NAME = "KEY_DRIVER_DISPLAY_NAME"
const val KEY_DRIVER_GOOGLE_ID = "KEY_DRIVER_GOOGLE_ID"
const val KEY_DRIVER_MOBILE_NUMBER = "KEY_DRIVER_MOBILE_NUMBER"
const val KEY_DRIVER_LOGIN_WITH_OAUTH = "KEY_DRIVER_LOGIN_WITH_OAUTH"
const val KEY_DRIVER_GOOGLE_GMAIL = "KEY_DRIVER_GOOGLE_GMAIL"
const val KEY_DRIVER_PHONE_LOGIN = "KEY_DRIVER_PHONE_LOGIN"
const val KEY_DRIVER_TAXI_NUMBER = "KEY_DRIVER_TAXI_NUMBER"
const val KEY_DRIVER_TAXI_MODEL = "KEY_DRIVER_TAXI_MODEL"
const val KEY_DRIVER_PROFILE_URL = "KEY_DRIVER_PROFILE_URL"
const val KEY_DRIVER_RATING = "KEY_DRIVER_RATING"
const val KEY_LOGIN_WITH_OAUTH = "KEY_LOGIN_WITH_OAUTH"

// Map Options
const val POLYLINE_COLOR = Color.RED
const val POLYLINE_WIDTH = 8f
const val MAP_ZOOM = 15f
const val MAP_VIEW_BUNDLE_KEY = "MapViewBundleKey"

//FireMessaging
const val NOTIFICATION_TITLE = "title"
const val NOTIFICATION_CONTENT = "body"
const val KEY_TOKEN_REFERENCE = "Token"





